import Head from 'next/head'
import Image from 'next/image'
import Web1 from '../public/web1.png'
import Web2 from '../public/web2.png'
import { useRouter } from 'next/router'

export default function Project() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Somying Phetdenlarp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900 px-10 min-h-screen">
        <section>
          <nav className="flex justify-between gap-10 mb-5 py-10">
            <h1
              className="font-logo font-semibold text-3xl text-gray-300 cursor-pointer"
              onClick={() => router.push('./')}
            >
              Mooks
            </h1>
            <div className="flex gap-10">
              <div
                className="items-center px-4 py-2 text-xl font-mono font-semibold text-white border-none rounded-md bg-gradient-to-r from-cyan-500 to-orange-400 shadow-md shadow-cyan-500/30 cursor-pointer"
                onClick={() => router.push('./project')}
              >
                Project
              </div>
            </div>
          </nav>
        </section>
        <section className="py-2 font-mono">
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href="https://safe-painness-six.vercel.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={'80%'}
                  height={'80%'}
                  layout="responsive"
                  src={Web1}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 ">
              <a href="https://food-recipes-jet.vercel.app/">
                <Image
                  className="rounded-lg object-cover"
                  width={'80%'}
                  height={'80%'}
                  layout="responsive"
                  src={Web2}
                  alt=""
                />
              </a>
            </div>
          </div>
        </section>
        <div className="text white text-3xl">test</div>
      </main>
    </>
  )
}
